// dict = open('espdic_small.txt').readlines
// json_dict = dict.map{|e| e.chomp.split(' : ')}.to_json.gsub("],","],\n")
// open('esperanto_english_dict.js','w'){|f| f.puts json_dict}

const esperanto_english_dict = [
  ["Aarono","Aaron"],
  ["Abadono","Abaddon (biblical","a compartment of Gehenna)"],
  ["abaĵuro","lampshade"],
  ["abako","abacus","ball frame","counting frame","calculating frame","chart"],
  ["abakteria","abacterial"],
  ["abaktio","abactio"],
  ["abandoni","to relinquish"],
  ["abandonismo","fear of abandonment"],
  ["abandono","abandonment","relinquishment"],
  ["abasido","Abbasid"],
  ["Abaso","Abbas"],
  ["abata","abbatial"],
  ["abata jurisdikcio","abbacy"],
  ["abateco","abbacy","abbotship"],
  ["abateja","abbatial"],
  ["abatejo","abbey"],
  ["abatina","abbatial"],
  ["abatineja","abbatial"],
  ["abatinejo","abbey"],
  ["abatino","abbess"],
  ["abatiso","barricade of trees or branches","abatis"],
  ["abatlando","abbacy"],
  ["abato","abbé","abbot"],
  ["abazia","abasic","abatic"],
  ["abazio","abasia (inability to walk caused by lack of muscular coordination)"],
  ["abceso","abscess"],
  ["abderano","fool"],
  ["abdika","abdication"],
  ["abdikado","abdication"],
  ["abdikanto","abdicant","abdicator"],
  ["abdikebla","abdicable"],
  ["abdiki","to abdicate","resign"],
  ["abdiko","abdication"],
  ["abdomena","abdominal"],
  ["abdomeno","abdomen","belly","lower part of the body"],
  ["abdukcia","abducent"],
  ["abdukcia muskolo","abductor"],
  ["abdukcii","to abduct"],
  ["abdukcio","abduction"],
  ["abduktado","abduction"],
  ["abdukti","to abduct"],
  ["abdukto","abduction"],
  ["abduktoro","abductor"],
  ["Abdulo","Abdul","Abdullah"],
  ["abeke","aback"],
  ["abela","Abel’s","Abelian","commutative (group)","related to bees"],
  ["abela kolonio","bee colony","settlement"],
  ["abela kriterio","Abel test"],
  ["abela ofrio","Orphys apifera","bee orchid"],
  ["Abelardo","Abelard"],
  ["abelaro","swarm of bees"]
];

export default esperanto_english_dict.map( pair => pair.map(s => s.toLowerCase() ) )